name: persistent_canvas
version: 1.0.1+1
description: Provides PersistentCanvas and PixelBuffer 
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/persistent_canvas
documentation: https://github.com/GreenAppers/persistent_canvas/wiki

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image: ^2.0.7
  scoped_model: ^1.0.1

