name: persistent_canvas
version: 1.0.2+2
description: Provides PersistentCanvas and PixelBuffer via PhotographTransducer
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/persistent_canvas
documentation: https://github.com/GreenAppers/persistent_canvas/wiki

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  busy_model: ^1.0.0
  flutter:
    sdk: flutter
  image:
    path: ../image
  scoped_model: ^1.0.1
